### ISSUE TITLE
Launch X

### ISSUE THREAD

**Issue by micbaires** [T0ny-dev/MisionFrontEnd-Launch-X-Latam#1]

**Comment by T0ny-dev** [comment]
Hola 💪 colega espero este muy bien 🚀 cualquier cosa aquí vamos estar.

**Comment by Zoale** [comment]
Hola T0ny, disculpa la molestia... He estado viendo el buen trabajo que has tenido en el proyecto de Css (La página de la vacuna) pero note un error de ortografía, y me gustaría mencionarlo por si deseas corregirlo, en el index.html, en la linea 34 en la parte del div: banner__tittle, escribiste figth en vez de fight. espero que te encuentres bien y excelente trabajo hermano :).
